version: '3.8'
services:

  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"

  app:
    container_name: genealogy-app
    image: app
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7688
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      FILE_STORAGE: /upload-dir
    ports:
      - "8080:8080"
    volumes:
      - ./upload-dir:/upload-dir
    depends_on:
      - neo4j
      - eureka-server

  app-user:
    container_name: genealogy-app-user
    image: app-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/genealogydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: genealogydb
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password1234
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4JLABS_PLUGINS: "apoc"
      NEO4J_dbms_security_procedures_whitelist: apoc.*
      NEO4J_dbms_security_procedures_unrestricted=: apoc.*
      apoc.export.file.enabled: "true"
      apoc.import.file.enabled: "true"
      apoc.import.file.use_neo4j_config: "true"
    ports:
      - "7688:7688"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
      - ./plugins:/plugins
      - ./upload-dir:/upload-dir

volumes:
  neo4j_data:
