version: '3.8'
services:
  app:
    container_name: genealogy-app
    image: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/genealogydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: genealogydb
    ports:
      - "5432:5432"

