POST http://localhost:8080/api/v1/genealogy/register
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Smith",
  "phone": "123456789",
  "username": "admin@admin.lol8",
  "password": "admin1234",
  "role": "ROLE_ADMIN"
}

###
POST http://localhost:8080/api/v1/genealogy/auth
Content-Type: application/json

{
  "username": "admin@admin.lol8",
  "password": "admin1234"
}
###

POST http://localhost:8080/api/v1/genealogy/tree
Content-Type: application/json

{
    "name": "Smith Family",
    "userId": 6
}

###

# curl -X POST "http://localhost:8080/api/v1/genealogy/tree/1/persons"
#     -H "Content-Type: application/json"
#     -d '{
#           "firstname": "John",
#           "lastname": "Smith",
#           "birthDate": "1980-01-01"
#         }'
POST http://localhost:8080/api/v1/genealogy/tree/3/persons
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Smith",
  "birthDate": "1980-01-01"
}

###


###

GET http://localhost:8080/api/v1/genealogy/all
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pQGFkbWltLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiQWRhIn0.Nc0aRKmCK1vxBnESM1xZT6IM741LPRobqkqPZzJGICA

###


GET http://localhost:8080/api/v1/genealogy/all/id
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pQGFkbWltLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiQWRhIn0.Nc0aRKmCK1vxBnESM1xZT6IM741LPRobqkqPZzJGICA
Content-Type: application/json

{
  "id": "1"
}

###

POST http://localhost:8080/api/v1/genealogy/register
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Smith",
  "phone": "123456789",
  "username": "userNeo4j@userNeo4j.com",
  "password": "user1234",
  "role": "ROLE_USER"
}

###
POST http://localhost:8080/api/v1/genealogy/login
Content-Type: application/json

{
  "username": "userNeo4j@userNeo4j.com",
  "password": "user1234"
}
###
DELETE http://localhost:8080/api/v1/genealogy/delete
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pQGFkbWltLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiQWRhIn0.Nc0aRKmCK1vxBnESM1xZT6IM741LPRobqkqPZzJGICA
Content-Type: application/json

{
  "username": "admi@adminnn.com"
}

###
